### ISSUE TITLE
Continue Training Question 

### ISSUE THREAD

**Issue by SelinaFelton** [facebookresearch/pythia#131]
## ❓ Questions and Help
Can LoRRA's training continue after the model is interrupted? If it can, how should I do it?

**Comment by apsdehal** [comment]
Use `--resume 1`, keeping rest of the arguments same.

**Comment by SelinaFelton** [comment]
Thanks, I will try.

**Comment by SelinaFelton** [comment]
I have another problem, how can I train LoRRA faster?  When I use 1 GPU(1080Ti, batch_size=128) to train LoRRA, it train 1000 iterations using 2 hours. 
When I set data_parallel=true to use multi-gpus, I meet the same problem as [https://github.com/facebookresearch/pythia/issues/77](url). Only num_workers<=2 works for me.
Setting distributed=true still dose not work for me.

**Comment by SelinaFelton** [comment]
When I use commond: 

> CUDA_VISIBLE_DEVICES=4,5,6,7_ nohup python -u tools/run.py --tasks vqa --datasets textvqa --model lorra --config configs/vqa/textvqa/lorra.yml --data_parallel=true > 0729-temp.log training_parameters.num_workers 4 2>&1 &

This is my out put:
> 2019-07-29T16:12:51 ERROR: DataLoader worker (pid 2963) is killed by signal: Killed. 
Traceback (most recent call last):
  File "tools/run.py", line 94, in <module>
    run()
  File "tools/run.py", line 83, in run
    trainer.train()
  File "/media/userdisk1/wy/pythia-0715/pythia/trainers/base_trainer.py", line 232, in train
    should_break = self._logistics(report)
  File "/media/userdisk1/wy/pythia-0715/pythia/trainers/base_trainer.py", line 322, in _logistics
    _, meter = self.evaluate(self.val_loader, single_batch=True)
  File "/media/userdisk1/wy/pythia-0715/pythia/trainers/base_trainer.py", line 374, in evaluate
    for batch in tqdm(loader, disable=not use_tqdm):
  File "/home/wangyan/anaconda3/envs/pythia03/lib/python3.6/site-packages/tqdm-4.19.9-py3.6.egg/tqdm/_tqdm.py", line 876, in __iter__
    for obj in iterable:
  File "/home/wangyan/anaconda3/envs/pythia03/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    idx, batch = self._get_batch()
  File "/home/wangyan/anaconda3/envs/pythia03/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 610, in _get_batch
    return self.data_queue.get()
  File "/home/wangyan/anaconda3/envs/pythia03/lib/python3.6/multiprocessing/queues.py", line 94, in get
    res = self._recv_bytes()
  File "/home/wangyan/anaconda3/envs/pythia03/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/wangyan/anaconda3/envs/pythia03/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/wangyan/anaconda3/envs/pythia03/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
  File "/home/wangyan/anaconda3/envs/pythia03/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 274, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 2963) is killed by signal: Killed.

**Comment by apsdehal** [comment]
This issue occurs only when you have less memory than expected for a batch size of 128. You will have to play with batch size and learning rate in that case so as to be able to fit smaller batch sizes in your memory. The distributed setup should work after the latest changes, make sure to pull and merge them. As you increase num_workers the memory consumption is bound to increase. Keep an eye on `htop` output for your machine. That will tell you your memory consumption and the point it fails. See relevant issue on maskrcnn-benchmark at https://github.com/facebookresearch/maskrcnn-benchmark/issues/195

**Comment by SelinaFelton** [comment]
Thanks! It's It is indeed my memory problem.
