### ISSUE TITLE
Environment support question

### ISSUE THREAD

**Issue by SelinaFelton** [facebookresearch/pythia#153]
## ❓ Questions and Help
Can Pythia train on 2080ti? If it can, which version of CUDA and cudnn should be installed?
This is my server's environment information:

> Collecting environment information...
>
> PyTorch version: 1.0.1.post2
> Is debug build: No
> CUDA used to build PyTorch: 9.0.176
> 
> OS: Ubuntu 16.04.5 LTS
> GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
> CMake version: version 3.5.1
> 
> Python version: 3.6
> Is CUDA available: Yes
> CUDA runtime version: 9.0.176
> GPU models and configuration: 
> GPU 0: GeForce RTX 2080 Ti
> GPU 1: GeForce RTX 2080 Ti
> GPU 2: GeForce RTX 2080 Ti
> GPU 3: GeForce RTX 2080 Ti
> GPU 4: GeForce RTX 2080 Ti
> GPU 5: GeForce RTX 2080 Ti
> GPU 6: GeForce RTX 2080 Ti
> GPU 7: GeForce RTX 2080 Ti
> 
> Nvidia driver version: 418.43
> cuDNN version: Probably one of the following:
> /usr/local/cuda-10.0/lib64/libcudnn.so
> /usr/local/cuda-10.0/lib64/libcudnn.so.7
> /usr/local/cuda-10.0/lib64/libcudnn.so.7.5.0
> /usr/local/cuda-10.0/lib64/libcudnn_static.a
> /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so
> /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7
> /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.1
> /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn_static.a
> /usr/local/cuda-9.0/lib64/libcudnn.so.7.3.0
> /usr/local/cuda-9.0/lib64/libcudnn_static.a
> /usr/local/lib/python2.7/dist-packages/cntk/libs/libcudnn.so.7
> 
> Versions of relevant libraries:
> [pip] Could not collect
> [conda] torch                     1.0.1.post2               <pip>
> [conda] torchtext                 0.3.1                     <pip>
> [conda] torchvision               0.2.2                     <pip>
> 

It works well on 1080ti. I have tried to to configure Pythia on a 2080ti server yesterday, but when I ran train command, I got cudnn error. 

> 2019-08-14T11:05:33 INFO: Loading tasks and data
2019-08-14T11:05:43 INFO: CUDA Device 0 is: GeForce RTX 2080 Ti
2019-08-14T11:05:49 ERROR: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
Traceback (most recent call last):
  File "tools/run.py", line 94, in <module>
    run()
  File "tools/run.py", line 82, in run
    trainer.load()
  File "/home/C/gcy/pythia-0715/pythia/trainers/base_trainer.py", line 44, in load
    self.load_model()
  File "/home/C/gcy/pythia-0715/pythia/trainers/base_trainer.py", line 115, in load_model
    self.model = self.model.to(self.device)
  File "/home/gcy/anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 381, in to
    return self._apply(convert)
  File "/home/gcy/anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/home/gcy/anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/home/gcy/anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/gcy/anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 117, in _apply
    self.flatten_parameters()
  File "/home/gcy/anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 113, in flatten_parameters
    self.batch_first, bool(self.bidirectional))
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

**Comment by apsdehal** [comment]
Please install pytorch using conda, it will automatically figure best version for you. See https://pytorch.org/get-started/locally/.
