### ISSUE TITLE
Unable to train BUTD model

### ISSUE THREAD

**Issue by pidugusundeep** [facebookresearch/pythia#177]
## ❓ Questions and Help
Traceback (most recent call last):
  File "/glob/intel-python/python3/lib/python3.6/multiprocessing/util.py", line 262, in _run_finalizers
    finalizer()
  File "/glob/intel-python/python3/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/u28740/PYTHIA2/lib/python3.6/shutil.py", line 486, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/home/u28740/PYTHIA2/lib/python3.6/shutil.py", line 444, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/home/u28740/PYTHIA2/lib/python3.6/shutil.py", line 442, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfs000000248832ae0d000004ee'
Traceback (most recent call last):
  File "/glob/intel-python/python3/lib/python3.6/multiprocessing/util.py", line 262, in _run_finalizers
    finalizer()
  File "/glob/intel-python/python3/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/u28740/PYTHIA2/lib/python3.6/shutil.py", line 486, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/home/u28740/PYTHIA2/lib/python3.6/shutil.py", line 444, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/home/u28740/PYTHIA2/lib/python3.6/shutil.py", line 442, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfs00000024031ab408000004ef'
Traceback (most recent call last):
  File "tools/run.py", line 94, in <module>
    run()
  File "tools/run.py", line 83, in run
    trainer.train()
  File "/home/u28740/generatePythiaTrainingset/pythia/pythia/trainers/base_trainer.py", line 239, in train
    report = self._forward_pass(batch)
  File "/home/u28740/generatePythiaTrainingset/pythia/pythia/trainers/base_trainer.py", line 259, in _forward_pass
    model_output = self.model(prepared_batch)
  File "/home/u28740/generatePythiaTrainingset/pythia/pythia/models/base_model.py", line 120, in __call__
    model_output = super().__call__(sample_list, *args, **kwargs)
  File "/home/u28740/PYTHIA2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/u28740/generatePythiaTrainingset/pythia/pythia/models/butd.py", line 140, in forward
    pi_t = data["texts"][:, t].unsqueeze(-1)
IndexError: index 52 is out of bounds for dimension 1 with size 52

I get this error while training how do i fix this ?

**Comment by apsdehal** [comment]
@vedanuj Can you look into this?

**Comment by vedanuj** [comment]
@pidugusundeep Can you share the config you are using to train the model? Did you make any changes to the default setup for BUTD in Pythia?

**Comment by pidugusundeep** [comment]
Nope i just added the `imdb_train.npy` with my own data and had the `.npy` files for each image file

**Comment by pidugusundeep** [comment]
I generated the features for the images using https://github.com/facebookresearch/pythia/blob/master/pythia/scripts/features/extract_features_vmb.py (changed to .png for my images) and then created the `imd_train.npy` as specified in this comment https://github.com/facebookresearch/pythia/issues/175#issuecomment-527900634

I had the same coco.yml file to run the training on my own data.

**Comment by vedanuj** [comment]
In `coco.yml` there is a param `max_length: 52`. Can you try changing it to maximum length of captions in your dataset?

**Comment by pidugusundeep** [comment]
Tried changing and it started running without any errors, Thanks. How much time does it take for the training normally?( estimate based on the number of images please provide system requirements as well).

**Comment by pidugusundeep** [comment]
![Screenshot from 2019-09-11 18-06-54](https://user-images.githubusercontent.com/10946649/64697708-15bc1300-d4bf-11e9-9ff6-667db4a1014f.png)
I have been training and it's almost `03:04:20` hours and the process doesn't show any progress is that normal? iam running on a CPU machine with multicore and not using GPU.

**Comment by vedanuj** [comment]
You can reduce the batch size and check if you see any iterations and numbers. I have never trained these networks on CPU so I don't have an estimate on the time it will take. But it will be very slow for sure on a CPU. Usually we train on multiple GPUs.

**Comment by pidugusundeep** [comment]
Thanks for the information btw how many sets of images are you using for training ??
