### ISSUE TITLE
COCO features showing errors

### ISSUE THREAD

**Issue by ggaemo** [facebookresearch/pythia#209]
## ❓ Questions and Help

Traceback (most recent call last):
  File "/home/jinwon/pythia/tools/pythia_run.py", line 94, in <module>
    run()
  File "/home/jinwon/pythia/tools/pythia_run.py", line 83, in run
    trainer.train()
  File "/home/jinwon/pythia/pythia/trainers/base_trainer.py", line 199, in train
    self.inference()
  File "/home/jinwon/pythia/pythia/trainers/base_trainer.py", line 421, in inference
    self._inference_run("test")
  File "/home/jinwon/pythia/pythia/trainers/base_trainer.py", line 425, in _inference_run
    self.predict_for_evalai(dataset_type)
  File "/home/jinwon/pythia/pythia/trainers/base_trainer.py", line 464, in predict_for_evalai
    for batch in tqdm(dataloader):
  File "/home/jinwon/.conda/envs/maskrcnn_benchmark/lib/python3.7/site-packages/tqdm/_tqdm.py", line 897, in __iter__
    for obj in iterable:
  File "/home/jinwon/.conda/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 551, in __next__
    return self._process_next_batch(batch)
  File "/home/jinwon/.conda/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 572, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
FileNotFoundError: Traceback (most recent call last):
  File "/home/jinwon/.conda/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/jinwon/.conda/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/jinwon/.conda/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/utils/data/dataset.py", line 85, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/home/jinwon/pythia/pythia/tasks/base_dataset.py", line 76, in __getitem__
    sample = self.get_item(idx)
  File "/home/jinwon/pythia/pythia/tasks/vqa/vqa2/dataset.py", line 95, in get_item
    return self.load_item(idx)
  File "/home/jinwon/pythia/pythia/tasks/vqa/vqa2/dataset.py", line 125, in load_item
    features = self.features_db[idx]
  File "/home/jinwon/pythia/pythia/tasks/features_dataset.py", line 29, in __getitem__
    return self.features_db[idx]
  File "/home/jinwon/pythia/pythia/tasks/features_dataset.py", line 117, in __getitem__
    image_features, infos = self._get_image_features_and_info(image_file_name)
  File "/home/jinwon/pythia/pythia/tasks/features_dataset.py", line 101, in _get_image_features_and_info
    image_feats, infos = self._read_features_and_info(feat_file)
  File "/home/jinwon/pythia/pythia/tasks/features_dataset.py", line 87, in _read_features_and_info
    feature, info = feature_reader.read(feat_file)
  File "/home/jinwon/pythia/pythia/tasks/feature_readers.py", line 67, in read
    feat = np.load(image_feat_path)
  File "/home/jinwon/.conda/envs/maskrcnn_benchmark/lib/python3.7/site-packages/numpy/lib/npyio.py", line 422, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/jinwon/pythia/pythia/../data/coco/detectron_fix_100/fc6/test2015/COCO_test2015_000000104073.npy'

the error above shows even after I downloaded the data set given by 
https://dl.fbaipublicfiles.com/pythia/features/coco.tar.gz

I checked the md5sum. Even after that the error above is appearing.

**Comment by apsdehal** [comment]
Can you check if the folder `/home/jinwon/pythia/pythia/../data/coco/detectron_fix_100/fc6/test2015` is present?

**Comment by ggaemo** [comment]
Yes it wass present, only certain files were missing. I downloaded again and unzipped it again and now it seems to work without missing files.
