### ISSUE TITLE
Quickstart guide for image captioning

### ISSUE THREAD

**Issue by yjxiao** [facebookresearch/pythia#214]
## ❓ Questions and Help

Currently, the quickstart guide only introduces using pythia for vqa. I've tried using the following similar steps to train BUTD from scratch but failed:

1. Install pythia as suggested in the doc (current master branch).
1. Download coco, coco_captions, detectron, and vocab files and extract to the `~/pythia/data` folder
2. Initialize training with `python tools/run.py --tasks captioning --datasets coco --model butd --config configs/captioning/coco/butd.yml`

The data folder is structured as:
```
data/
├── coco/
│   ├── detectron_fix_100/
│   └── resnet152/
├── detectron/
│   └──fc6/
├── imdb/
│   └── coco_captions/
└── vocabs/
    ├── vocabulary_100k.txt
    ├── vocabulary_captioning_thresh5.txt
    └── ...
```

The complete error stack is:
```
Traceback (most recent call last):
  File "tools/run.py", line 94, in <module>
    run()
  File "tools/run.py", line 83, in run
    trainer.train()
  File "$HOME/pythia/pythia/trainers/base_trainer.py", line 239, in train
    report = self._forward_pass(batch)
  File "$HOME/pythia/pythia/trainers/base_trainer.py", line 259, in _forward_pass
    model_output = self.model(prepared_batch)
  File "$HOME/pythia/pythia/models/base_model.py", line 120, in __call__
    model_output = super().__call__(sample_list, *args, **kwargs)
  File "$HOME/miniconda3/envs/pythia/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "$HOME/pythia/pythia/models/butd.py", line 140, in forward
    "image", sample_list, embedding[:, 0, :], batch_size_t=batch_size_t
  File "$HOME/pythia/pythia/models/pythia.py", line 262, in process_feature_embedding
    embedding, attention = feature_embedding_model(*inp)
  File "$HOME/miniconda3/envs/pythia/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "$HOME/pythia/pythia/modules/embeddings.py", line 206, in forward
    image_feat_variable, question_embedding, image_dims
  File "$HOME/miniconda3/envs/pythia/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "$HOME/pythia/pythia/modules/attention.py", line 34, in forward
    return self.module(*args, **kwargs)
  File "$HOME/miniconda3/envs/pythia/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "$HOME/pythia/pythia/modules/attention.py", line 138, in forward
    joint_feature = self.combination_layer(image_feat, question_embedding)
  File "$HOME/miniconda3/envs/pythia/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "$HOME/pythia/pythia/modules/layers.py", line 182, in forward
    return self.module(*args, **kwargs)
  File "$HOME/miniconda3/envs/pythia/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "$HOME/pythia/pythia/modules/layers.py", line 349, in forward
    torch.cat([h2, image_feat_mean, embedding], dim=1), (h1, c1)
RuntimeError: invalid argument 0: Tensors must have same number of dimensions: got 2 and 3 at /opt/conda/conda-bld/pytorch_1573049306803/work/aten/src/THC/generic/THCTensorMath.cu:62
```

Not sure what I missed or did wrong. Any help is appreciated.

**Comment by yjxiao** [comment]
The issue seems to be related to #203. The fix in #203 assumes an inference type of greedy during training while the default `butd.yml` uses beam search with size 1.
