### ISSUE TITLE
Size mismatch for classifier.module.weight

### ISSUE THREAD

**Issue by ankushtale** [facebookresearch/pythia#232]
## 🐛 Bug

Getting the following error while running inference for M4Ccaptioner base model.

Error:
RuntimeError: Error(s) in loading state_dict for M4C:
	size mismatch for classifier.module.weight: copying a param with shape torch.Size([6736, 768]) from checkpoint, the shape in current model is torch.Size([5000, 768]).
	size mismatch for classifier.module.bias: copying a param with shape torch.Size([6736]) from checkpoint, the shape in current model is torch.Size([5000]).

## Command
python tools/run.py --tasks vqa --datasets m4c_textvqa --model m4c \
--config configs/vqa/m4c_textvqa/m4c.yml \
--save_dir save/m4c \
--run_type val \
--resume_file data/models/m4c_textcaps_m4c_captioner.ckpt

## To Reproduce

python tools/run.py --tasks vqa --datasets m4c_textvqa --model m4c \
--config configs/vqa/m4c_textvqa/m4c.yml \
--save_dir save/m4c \
--run_type val \
--resume_file data/models/m4c_textcaps_m4c_captioner.ckpt

Error:
RuntimeError: Error(s) in loading state_dict for M4C:
	size mismatch for classifier.module.weight: copying a param with shape torch.Size([6736, 768]) from checkpoint, the shape in current model is torch.Size([5000, 768]).
	size mismatch for classifier.module.bias: copying a param with shape torch.Size([6736]) from checkpoint, the shape in current model is torch.Size([5000]).

**Comment by ankushtale** [comment]
@apsdehal  @ronghanghu any help is much appreciated

**Comment by ronghanghu** [comment]
@ankushtale Do you want to run M4C (for visual question answering) or M4C-Captioner (for image captioning)? It seems that you are loading M4C config with M4C-Captioner weights.

For M4C:
```
python tools/run.py --tasks vqa --datasets m4c_textvqa --model m4c \
--config configs/vqa/m4c_textvqa/m4c.yml \
--save_dir save/m4c \
--run_type val \
--resume_file data/models/m4c_textvqa_m4c.ckpt
```

For M4C-Captioner:
```
python tools/run.py --tasks captioning --datasets m4c_textcaps --model m4c_captioner \
--config configs/captioning/m4c_textcaps/m4c_captioner.yml \
--save_dir save/m4c_captioner \
--run_type val --evalai_inference 1 \
--resume_file data/models/m4c_textcaps_m4c_captioner.ckpt
```

**Comment by gokulanv** [comment]
@apsdehal @ronghanghu 
I used the M4C-Captioner for running inference as mentioned above: 
And I always get this error.

`2020-04-15T22:20:00 INFO: Starting val inference for evalai
2020-04-15T22:20:00 INFO: Predicting for m4c_textcaps
  0% 0/25 [00:00<?, ?it/s]2020-04-15T22:20:01 ERROR: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataset.py", line 207, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/content/pythia/pythia/datasets/base_dataset.py", line 76, in __getitem__
    sample = self.get_item(idx)
  File "/content/pythia/pythia/datasets/vqa/vqa2/dataset.py", line 95, in get_item
    return self.load_item(idx)
  File "/content/pythia/pythia/datasets/vqa/m4c_textvqa/dataset.py", line 82, in load_item
    features = self.features_db[idx]
  File "/content/pythia/pythia/datasets/features_dataset.py", line 29, in __getitem__
    return self.features_db[idx]
  File "/content/pythia/pythia/datasets/features_dataset.py", line 117, in __getitem__
    image_features, infos = self._get_image_features_and_info(image_file_name)
  File "/content/pythia/pythia/datasets/features_dataset.py", line 101, in _get_image_features_and_info
    image_feats, infos = self._read_features_and_info(feat_file)
  File "/content/pythia/pythia/datasets/features_dataset.py", line 87, in _read_features_and_info
    feature, info = feature_reader.read(feat_file)
  File "/content/pythia/pythia/datasets/feature_readers.py", line 66, in read
    feat = np.load(image_feat_path)
  File "/usr/local/lib/python3.6/dist-packages/numpy/lib/npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/content/pythia/pythia/../data/open_images/detectron_fix_100/fc6/train/acd7649af3a05139.npy'

Traceback (most recent call last):
  File "tools/run.py", line 86, in <module>
    run()
  File "tools/run.py", line 75, in run
    trainer.train()
  File "/content/pythia/pythia/trainers/base_trainer.py", line 198, in train
    self.inference()
  File "/content/pythia/pythia/trainers/base_trainer.py", line 424, in inference
    self._inference_run("val")
  File "/content/pythia/pythia/trainers/base_trainer.py", line 431, in _inference_run
    self.predict_for_evalai(dataset_type)
  File "/content/pythia/pythia/trainers/base_trainer.py", line 470, in predict_for_evalai
    for batch in tqdm(dataloader):
  File "/usr/local/lib/python3.6/dist-packages/tqdm/std.py", line 1091, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataset.py", line 207, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/content/pythia/pythia/datasets/base_dataset.py", line 76, in __getitem__
    sample = self.get_item(idx)
  File "/content/pythia/pythia/datasets/vqa/vqa2/dataset.py", line 95, in get_item
    return self.load_item(idx)
  File "/content/pythia/pythia/datasets/vqa/m4c_textvqa/dataset.py", line 82, in load_item
    features = self.features_db[idx]
  File "/content/pythia/pythia/datasets/features_dataset.py", line 29, in __getitem__
    return self.features_db[idx]
  File "/content/pythia/pythia/datasets/features_dataset.py", line 117, in __getitem__
    image_features, infos = self._get_image_features_and_info(image_file_name)
  File "/content/pythia/pythia/datasets/features_dataset.py", line 101, in _get_image_features_and_info
    image_feats, infos = self._read_features_and_info(feat_file)
  File "/content/pythia/pythia/datasets/features_dataset.py", line 87, in _read_features_and_info
    feature, info = feature_reader.read(feat_file)
  File "/content/pythia/pythia/datasets/feature_readers.py", line 66, in read
    feat = np.load(image_feat_path)
  File "/usr/local/lib/python3.6/dist-packages/numpy/lib/npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/content/pythia/pythia/../data/open_images/detectron_fix_100/fc6/train/acd7649af3a05139.npy'
`

**Comment by ronghanghu** [comment]
Hi @ankushtale, you need to down the visual features (object features and OCR features) from for the TextCaps images, following the download links here: https://github.com/facebookresearch/pythia/tree/project/m4c/projects/M4C_Captioner#getting-data

**Comment by gokulanv** [comment]
But these files (/content/pythia/pythia/../data/open_images/detectron_fix_100/fc6/train) are around 400 GB right? (I saw this size in one of the issues).

Is there any workaround that uses less amount of data to just run the inference?

**Comment by ronghanghu** [comment]
> But these files (/content/pythia/pythia/../data/open_images/detectron_fix_100/fc6/train) are around 400 GB right? (I saw this size in one of the issues).
> 
> Is there any workaround that uses less amount of data to just run the inference?

It's roughly 33 GB altogether. You only need to download the TextCaps dataset features from https://github.com/facebookresearch/pythia/tree/project/m4c/projects/M4C_Captioner#getting-data

**Comment by ankushtale** [comment]
Hi @ronghanghu , thank you so much for your assistance! 
I was hoping to get one more help. Currently, we are running Pythia on GCP which is CPU only. And I guess in the evaluation phase, torch compulsorily expects NVIDIA GPU and throws an error in its absence.
On top of your mind, can you suggest a change to convert the code for CPU use only?

**Comment by ankushtale** [comment]
NVM, got it working with GPU. Thanks alot @ronghanghu for the earlier advice!

Note for anyone else stuck implementing the code. Running inferences requires about 76GB storage and 16GB RAM. If you don't have it, try it on any cloud service (GCP, DigitalOcean, AWS). Make sure you choose GPU enabled VM and install compatible CUDA drivers (>9.0).
