### ISSUE TITLE
ERROR: 'BaseTrainer' object has no attribute 'args'

### ISSUE THREAD

**Issue by mandliya** [facebookresearch/pythia#73]
I followed the instructions on the https://learnpythia.readthedocs.io/ to setup. I seem to have everything installed, and I could run the collab notebook locally. 

However, when I am trying to run the below command to try out inferences:

python tools/run.py --tasks vqa --datasets textvqa --model lorra --config configs/vqa/textvqa/lorra.yml \
--run_type val --evalai_inference 1 --resume_file data/models/lorra_best.pth

I am getting below error:

}
2019-05-29T20:25:41 INFO: Loading tasks and data
2019-05-29T20:25:44 INFO: CUDA Device 0 is: GeForce GTX 1080 Ti
2019-05-29T20:25:46 INFO: Torch version is: 1.0.0
2019-05-29T20:25:46 ERROR: 'BaseTrainer' object has no attribute 'args'
Traceback (most recent call last):
  File "tools/run.py", line 94, in <module>
    run()
  File "tools/run.py", line 82, in run
    trainer.load()
  File "/root/pythia/pythia/trainers/base_trainer.py", line 46, in load
    self.load_extras()
  File "/root/pythia/pythia/trainers/base_trainer.py", line 139, in load_extras
    self.checkpoint = Checkpoint(self)
  File "/root/pythia/pythia/utils/checkpoint.py", line 28, in __init__
    self.ckpt_foldername += foldername_from_config_override(self.trainer.args)
AttributeError: 'BaseTrainer' object has no attribute 'args'

I seem to be doing something wrong, any help would be great. I didn't change any code or config yet.

**Comment by apsdehal** [comment]
Apologies, this broke in recent PR #65. We are fixing this asap.

**Comment by apsdehal** [comment]
@mandliya this should be fixed now. Can you try again?

**Comment by mandliya** [comment]
Thanks for quick turnaround!
